sudo: required

language: node_js
node_js:
  - "5"

services:
  - docker

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t containx/kirk .
  - docker tag containx/kirk containx/kirk:$TRAVIS_BUILD_NUMBER
  - docker run -d -p 127.0.0.1:8080:8080 --name kirk containx/kirk

script:
  - docker ps | grep -q netshare

after_success:
  - docker push containx/kirk
  - docker push containx/kirk:$TRAVIS_BUILD_NUMBER
  - docker run -e DEPCON_MODE=$DEPCON_MODE -e MARATHON_HOST=$MARATHON_HOST -e MARATHON_USER=$MARATHON_USER -e MARATHON_PASS=$MARATHON_PASS -v $PWD:/data containx/kirk app create /data/depcon.yml -p VERSION=$TRAVIS_BUILD_NUMBER -p SLACK_CLIENT_ID=$SLACK_CLIENT_ID -p SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET --wait --force

# whitelist
branches:
  only:
    - master
