version: "2"
services:
  kirk:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      APP_ENV: development
    volumes:
      - ./:/go/src/github.com/jeremyroberts0/kirk
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./~/data/mongodb/db:/data/db
    ports:
      - "27017:27017"