version: "2"
services:
  kirk:
    build:
      context: .
    environment:
      APP_ENV: development
    networks:
      - my-net
    volumes:
      - ./:/go/src/github.com/jeremyroberts0/kirk
networks:
  my-net:
    driver: bridge